project:
  type: book

book:
  title: "Den långa bluffen"
  author: "Christian Lindell & Alex Voronov"
  date: "2026-02-23"
  chapters:
    - index.qmd
    - vad_ar_sysselsattning.qmd
    - flyktingar_vt.qmd
    - utsatta_omraden_regso.qmd
    - yrken_gfb.qmd
    - medianalder.qmd
    - fland_sysgrad.qmd
    - sys_eu_heltid_deltid.qmd
    - errata.qmd
    - references.qmd


bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



