project:
  type: book

book:
  title: "Den långa bluffen"
  author: "Christian Lindell & Alex Voronov"
  date: "2026-02-23"
  chapters:
    - index.qmd
    - jobbluffen.qmd
    - attflyttamalstolpar.qmd
    - krisibefolkningfragan.qmd
    - debespottade.qmd
    - mytenom2015.qmd
    - sveketmotukrainarna.qmd
    - femskottifoten.qmd
    - sammanfattning.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



