---
title: "Recensioner"
---

Här kommer ett urval av recensioner av "Den långa bluffen":

"Med saklig prosa och tydliga tabeller skingrar Lindell och Voronov de dimridåer som omgärdat migrationsdebatten. De har skrivit en av de senaste årens viktigaste böcker om svensk politik.". Joel Haldorf, Expressen, [länk](https://www.expressen.se/kultur/darfor-floppar-tidos--atervandringsprojekt/).

"Tålmodigt och metodiskt betar de sig igenom de överdrifter som har blivit vardagsmat i denna fråga; de som paras med radikal retorik och inte sällan landar i rena lögner, som sedan läggs till grund för både debatten och lagstiftningen." Moa Berglöf, Sydsvenskan, [länk](https://www.sydsvenskan.se/opinion/moa-berglof/nu-synas-lognerna-om-invandringen/).

"De har gått igenom statistik om invandring, arbetsmarknad och bidrag. De har vänt på siffrorna, jämfört över tid och lyckas sticka hål på det de kallar den långa bluffen, eller myten, om att Sverige är ett land som går på knäna på grund av för hög invandring. " Sofia Mirjamsdotter, Västerbottenkuriren, [länk](https://www.vk.se/2026-06-01/mirjamsdotter-det-ar-dags-att-krossa-myten-om-flyktingkrisen-cc9b7).

"Och när Ulf Kristersson påstår att Sverige är "ett land där fler och fler ska leva på färre och färre människors arbete" (vilket han sa i SVT:s partiledardebatt den 10 oktober 2021) så kontrar Lindell och Voronov, med hjälp av statistik, med att Sverige i själva verket inte haft en lägre andel försörjda av sociala ersättningar på 50 år" Anders Q Björkman, SvD, [länk](https://www.svd.se/a/q6vKX0/ny-bok-om-myterna-politiker-presenterar-om-invandring).

”De arbetar sig igenom statistik. De pratar med människor. De synar korten. Och de skriver med stilsäker lätthet. Det är en underbar liten folkbildande bok. Deras kalla siffror kan både spräcka valrörelsens entonighet och rädda konversationen vid varenda sommarmiddag.” Per Wirtén, GP, [länk](https://www.gp.se/kultur/litteratur/litteraturrecension/recension-den-langa-bluffen-av-alex-voronov-och-christian-lindell.80cd3678-a952-4f49-8755-627077d4d586).

"I detta landskap släpps Den långa bluffen av Alex Voronov och Christian Lindell. Bokens främsta ambition är att syna en påstådd bluff kring invandring och invandringspolitik. Det görs förtjänstfullt genom att jämföra statistik över migration och arbetsmarknadsintegration med politikens förändrade syn på invandring." Martin Nordin, Arbetet, [länk](https://arbetet.se/2026/06/18/2015-ars-flyktingkris-har-inte-fatt-de-negativa-konsekvenser-som-det-varnats-for/).

"Även om jag hade önskat ett större erkännande av tidigare forskning är ”Den långa bluffen” som frisk luft i ett mögelskadat rum." Rasmus Landström, Aftonbladet, [länk](https://www.aftonbladet.se/kultur/bokrecensioner/a/5pjpxe/den-langa-bluffen-och-framlingsnationen-recenseras-av-rasmus-landstrom).